const { db } = require('../db');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');

const STORAGE_DIR = path.join(__dirname, '..', '..', 'storage', 'submissions');
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY || '';

// House crab user — created on first use
function getHouseCrabUser() {
  let user = db.prepare("SELECT * FROM users WHERE username = 'HouseCrab'").get();
  if (!user) {
    const id = crypto.randomUUID();
    db.prepare(
      "INSERT INTO users (id, username, agent_name, rating, rating_deviation, tier) VALUES (?, 'HouseCrab', 'HouseCrab AI', 1500, 350, 'Silver')"
    ).run(id);
    user = db.prepare('SELECT * FROM users WHERE id = ?').get(id);
  }
  return user;
}

async function generateHouseSubmission(challengePrompt, challengeCategory) {
  if (!ANTHROPIC_API_KEY) {
    console.error('ANTHROPIC_API_KEY not set — house crab cannot generate');
    return null;
  }

  const systemPrompt = `You are an AI coding assistant competing in a timed challenge. Build a complete, self-contained web application in a single index.html file. The output must work standalone in a browser with no external dependencies (CDN libraries are OK). Make it functional, visually polished, and impressive. Output ONLY the HTML code, nothing else — no markdown fences, no explanation.`;

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 8000,
        system: systemPrompt,
        messages: [{
          role: 'user',
          content: challengePrompt,
        }],
      }),
    });

    if (!res.ok) {
      const text = await res.text();
      console.error('House crab API error:', res.status, text);
      return null;
    }

    const data = await res.json();
    let html = data.content[0]?.text || '';

    // Strip markdown fences if present
    if (html.startsWith('```')) {
      html = html.replace(/^```html?\n?/, '').replace(/\n?```$/, '');
    }

    if (!html.includes('<html') && !html.includes('<!DOCTYPE')) {
      console.error('House crab generated invalid HTML');
      return null;
    }

    return html;
  } catch (err) {
    console.error('House crab generation failed:', err.message);
    return null;
  }
}

async function matchWithHouseCrab(playerSubmissionId, challengeId, challengePrompt, challengeCategory) {
  const houseCrab = getHouseCrabUser();

  const html = await generateHouseSubmission(challengePrompt, challengeCategory);
  if (!html) return null;

  // Save house crab submission
  const submissionId = crypto.randomUUID();
  const folderPath = path.join(STORAGE_DIR, submissionId);
  fs.mkdirSync(folderPath, { recursive: true });
  fs.mkdirSync(path.join(folderPath, 'src'), { recursive: true });
  fs.writeFileSync(path.join(folderPath, 'index.html'), html, 'utf-8');
  fs.writeFileSync(path.join(folderPath, 'crabs.json'), JSON.stringify({
    model: 'claude-sonnet-4',
    harness: 'claude-api',
    submitted_at: new Date().toISOString(),
  }), 'utf-8');
  fs.writeFileSync(path.join(folderPath, 'src', 'notes.md'), 'Generated by HouseCrab AI', 'utf-8');

  const breakdown = {
    status: 'pending',
    message: 'AI referee not yet wired — community vote is the live signal.',
  };

  db.prepare(`
    INSERT INTO submissions (id, challenge_id, user_id, folder_path, ai_score, ai_breakdown, model, harness, time_elapsed)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    submissionId, challengeId, houseCrab.id, submissionId,
    null, JSON.stringify(breakdown),
    'claude-sonnet-4', 'claude-api', null
  );

  // Create battle
  const battleId = crypto.randomUUID();
  db.prepare(`
    INSERT INTO battles (id, challenge_id, submission_a_id, submission_b_id)
    VALUES (?, ?, ?, ?)
  `).run(battleId, challengeId, playerSubmissionId, submissionId);

  console.log(`House crab matched: battle ${battleId.slice(0, 8)}…`);
  return battleId;
}

module.exports = { matchWithHouseCrab };
